---
apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init-v1
  namespace: airflow
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: airflow
      volumes:
        - name: pod-template-file
          configMap:
            name: airflow-config-kubernetes-template
            defaultMode: 0444
        - name: dagbags
          configMap:
            name: airflow-dagbags
            defaultMode: 0444
        - name: scripts
          configMap:
            name: airflow-scripts
            defaultMode: 0555
        - name: secrets
          secret:
            secretName: airflow-secrets
      containers:
        - name: airflow-init
          image: apache/airflow:1.10.14-python3.7
          volumeMounts:
            - name: pod-template-file
              mountPath: /opt/airflow/k8
              readOnly: true
            - name: dagbags
              mountPath: /opt/airflow/dags
              readOnly: true
            - name: scripts
              mountPath: /opt/airflow/scripts
              readOnly: true
            - name: secrets
              mountPath: /opt/airflow/secrets
              readOnly: true
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: KubernetesExecutor
            - name: AIRFLOW__KUBERNETES__NAMESPACE
              value: airflow
            - name: AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE
              value: /opt/airflow/k8/airflow_template.yml
          envFrom:
            - configMapRef:
                name: airflow-config-core
            - configMapRef:
                name: airflow-config-secrets
            - configMapRef:
                name: airflow-config-cli
            - configMapRef:
                name: airflow-config-api
            - configMapRef:
                name: airflow-config-operators
            - configMapRef:
                name: airflow-config-webserver
            - configMapRef:
                name: airflow-config-email
            - configMapRef:
                name: airflow-config-scheduler
            - secretRef:
                name: airflow-smtp
            - secretRef:
                name: airflow-fernet-key
            - secretRef:
                name: airflow-webserver-flask-key
            - secretRef:
                name: airflow-db-connection
          command:
            - python
          args:
            - /opt/airflow/scripts/airflow-init.py