apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  type: NodePort
  ports:
  - name: worker
    port: 9200
    protocol: TCP
    targetPort: 9200
    nodePort: 30092
  - name: admin
    port: 9300
    protocol: TCP
    targetPort: 9300
    nodePort: 30093
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  type: NodePort
  ports:
    - name: worker
      port: 5601
      protocol: TCP
      targetPort: 5601
      nodePort: 30601
  selector:
    app: kibana