---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: keycloak-standalone
    files:
      - standalone-ha.xml
    options:
      disableNameSuffixHash: true