apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  template:
    spec:
      volumes:
        - name: clin-themes
          emptyDir: {}
      initContainers:
        - name: clone-clin-theme
          image: ferlabcrsj/git-autosync:10d22c3cab424f19ba9ffc2287aa96170195b27a
          imagePullPolicy: IfNotPresent
          command:
            - git
            - clone
          args:
            - https://github.com/Ferlab-Ste-Justine/clin-keycloak-theme.git
            - /opt/clin-themes
          volumeMounts:
            - name: clin-themes
              mountPath: /opt/clin-themes
      containers:
        - name: keycloak
          volumeMounts:	
            - name: clin-themes
              mountPath: /opt/jboss/keycloak/themes/clin-keycloak-theme