apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:
        - name: keycloak
          image: ferlabcrsj/cqdg-keycloak:59edb2d91e23a495a058b417a3144876d3660da6
          volumeMounts:	
            - name: keycloak-standalone	
              mountPath: /opt/jboss/keycloak/standalone/configuration/standalone-ha.xml	
              subPath: standalone-ha.xml
      volumes:
        - name: keycloak-standalone
          configMap:
            name: keycloak-standalone