apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cqdg-orchestrations/keycloak
  - db.yml
  - services.yml
  - secrets.yml

patchesStrategicMerge:
  - overrides.yml

configMapGenerator:
  - name: jars-list
    options:
      disableNameSuffixHash: true
    files:
      - jars_list.json