apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../dev/cqdg-orchestrations/keycloak-v11
  - db.yml
  - services.yml
  - secrets.yml

patchesStrategicMerge:
  - overrides.yml