apiVersion: v1
kind: Service
metadata:
  name: keycloak-external
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30881
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: "keycloak"