---
apiVersion: v1
kind: ConfigMap
metadata:
  name: git-autosync-listing
  namespace: terraform
data:
  listing.json: |
    [
      {
          "path": "/opt/clin-keycloak-configs",
          "repo": "git@github.com:Ferlab-Ste-Justine/clin-keycloak-configs.git",
          "branch": "main"
      },
      {
          "path": "/opt/cqdg-keycloak-configs",
          "repo": "git@github.com:Ferlab-Ste-Justine/cqdg-keycloak-configs.git",
          "branch": "main"
      }
    ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: git-autosync-listing
data:
  listing.json: |
    [
      {
          "path": "/opt/clin-keycloak-theme",
          "repo": "https://github.com/Ferlab-Ste-Justine/clin-keycloak-theme.git",
          "branch": "master"
      },
      {
          "path": "/opt/airflow-dags/cqdg",
          "repo": "https://github.com/Ferlab-Ste-Justine/cqdg-dags.git",
          "branch": "main"
      }
    ]