apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backup.yml
  - prune-backups.yml
  - restores

configMapGenerator:
  - name: keycloak-db-connection
    options:
      disableNameSuffixHash: true
    literals:
      - PGDATABASE=keycloak_qa
      - PGHOST=postgres-server-qa
  - name: keycloak-db-connection-tls
    options:
      disableNameSuffixHash: true
    literals:
      - PGSSLMODE=verify-full
      - PGSSLROOTCERT=/opt/ca/ca.pem
  - name: keycloak-s3-backups
    options:
      disableNameSuffixHash: false
    literals:
      - S3_ENDPOINT=https://s3.ops.cqdg.ferlab.bio
      - S3_BUCKET=cqdg-qa-app-keycloak-backups
      - S3_REGION=RegionOne
      #15 days
      - S3_BACKUP_MAX_AGE="1296000"
