apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  annotations:
    fluxcd.io/automated: 'true'
spec:
  template:
    spec:
      containers:
      - image: chusj/cqdg-portal-ui:bd6c9e5a9d9a5e5a50822af3026847f13257097d
        name: portal
