apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  annotations:
    fluxcd.io/automated: 'true'
spec:
  template:
    spec:
      containers:
      - image: ferlabcrsj/cqdg-portal-ui:adaad746b15252db1f3923a5042a14fb7bcf68bf
        name: portal
