apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common/portal
  - ingresses.yml

patchesStrategicMerge:
  - deployments.yml

configMapGenerator:
  - name: cqdg-portal-configs
    options:
      disableNameSuffixHash: false
    literals:
      - API_URL=https://data-api.qa.cqdg.ferlab.bio
      - KEYCLOAK_URL=https://auth.qa.cqdg.ferlab.bio/auth
      - CLINICAL_DATA_API=https://clinical-data-api.qa.cqdg.ferlab.bio/api
      - DATA_STORAGE_API=https://datagrid-api.qa.cqdg.ferlab.bio