---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-ceph
  namespace: spark
  labels:
    name: spark
data:
  spark-ceph.conf: |
    spark.app.name=spark-ceph
    spark.executor.instances=5
    spark.kubernetes.container.image=chusj/spark:ace09476a0a5b51c90e1116c9d48ccbcd982e93e
    spark.hadoop.fs.s3a.endpoint=https://esc.calculquebec.ca:8080
