---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arranger-server
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: arranger-server
      containers:
      - image: ferlabcrsj/cqdg-arranger:6211b3ae0011fce54847ed07c86bdd5e266de3ed
        name: arranger-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: portal
      containers:
      - image: ferlabcrsj/cqdg-portal:ec358d1ab39b4ca0682c20e9b8d392c1a4d2d59b
        name: portal
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: keycloak
      containers:
      - image: ferlabcrsj/cqdg-keycloak:d0fd891d7dcbaf00b533fd2eb3d9bae68f0c1184
        name: keycloak
