---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: keycloak
      containers:
      - image: ferlabcrsj/cqdg-keycloak:45f8026f0c7fcd0dcdbb47e096f4cd1918bb85fa
        name: keycloak
