---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: keycloak
      containers:
      - image: ferlabcrsj/cqdg-keycloak:45f8026f0c7fcd0dcdbb47e096f4cd1918bb85fa
        name: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arranger-server
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: arranger-server
      containers:
      - image: ferlabcrsj/cqdg-arranger:a349f2b25ad42d3d6738af4752235862ce526b84
        name: arranger-server

