---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arranger-server
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: arranger-server
      containers:
      - image: ferlabcrsj/cqdg-arranger:974b85ec2c204d136739d94090128c6b7bee79e0
        name: arranger-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: portal
      containers:
      - image: ferlabcrsj/cqdg-portal:ec358d1ab39b4ca0682c20e9b8d392c1a4d2d59b
        name: portal
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: keycloak
      containers:
      - image: ferlabcrsj/cqdg-keycloak:45f8026f0c7fcd0dcdbb47e096f4cd1918bb85fa
        name: keycloak
