---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: airflow-backup
spec:
  schedule: "0 */4 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 1
      template:
        spec:
          imagePullSecrets:
            - name: images-pull
          restartPolicy: Never
          containers:
            - image: ferlabcrsj/postgres-backup:9bb43092f76e95f17cd09f03a27c65d84112a3cd
              name: airflow-backup
              command:
                - python3
                - /opt/backup.py
              env:
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-qa-airflow-credentials
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-qa-airflow-credentials
                      key: password
              envFrom:
                - secretRef:
                    name: s3-airflow-credentials
                - configMapRef:
                    name: airflow-s3-backups
                - configMapRef:
                    name: airflow-db-connection
                - configMapRef:
                    name: airflow-db-connection-tls
              volumeMounts:
                - name: ca-certificate
                  mountPath: /opt/ca
                  readOnly: true
          volumes:
            - name: ca-certificate
              secret:
                secretName: postgres-qa-ca-certificate
                defaultMode: 0555