apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
spec:
  template:
    spec:
      serviceAccountName: fluentd
      containers:
        - name: fluentd
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: "logs-store.default.svc.cluster.local"
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 1Gi
