apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
spec:
  type: NodePort
  ports:
    - name: cluster
      port: 7077
      nodePort: 31000
    - name: http
      port: 80
      nodePort: 31001