apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
spec:
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  dnsNames:
    - dev.cqdg.ferlab.bio
    - auth.dev.cqdg.ferlab.bio
    - portal.dev.cqdg.ferlab.bio
    - data-api.dev.cqdg.ferlab.bio
    - clinical-data-api.dev.cqdg.ferlab.bio