---
apiVersion: batch/v1
kind: Job
metadata:
  name: spark-ceph
  namespace: spark
spec:
  template:
    spec:
      containers:
      - name: ceph
        env:
          - name: SPARK_CLASS
            value: bio.ferlab.clin.etl.TestCeph
          - name: SPARK_JAR
            value: s3a://spark/test-ceph.jar