apiVersion: v1
kind: ConfigMap
metadata:
  name: zeppelin-server-conf-map
data:
  SERVICE_DOMAIN: notebook.qa.cqdg.ferlab.bio:80
  ZEPPELIN_K8S_SPARK_CONTAINER_IMAGE: chusj/spark:7508c20ef44952f1ee2af91a26822b6efc10998f
  ZEPPELIN_K8S_CONTAINER_IMAGE: chusj/zeppelin:7508c20ef44952f1ee2af91a26822b6efc10998f