---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: datagrid-service-backup
spec:
  schedule: "20 */4 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800
      backoffLimit: 2
      template:
        spec:
          imagePullSecrets:
            - name: images-pull
          restartPolicy: Never
          volumes:
            - name: ca-certificate
              secret:
                secretName: postgres-ca-certificate
                defaultMode: 0555
          containers:
            - image: ferlabcrsj/postgres-backup:9bb43092f76e95f17cd09f03a27c65d84112a3cd
              name: datagrid-service-backup
              command:
                - python3
                - /opt/backup.py
              env:
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: datagrid-service-db-credentials
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: datagrid-service-db-credentials
                      key: password
              envFrom:
                - secretRef:
                    name: s3-datagrid-service-credentials
                - configMapRef:
                    name: datagrid-service-s3-backups
                - configMapRef:
                    name: datagrid-service-db-connection
                - configMapRef:
                    name: datagrid-service-db-connection-tls
              volumeMounts:
                - name: ca-certificate
                  mountPath: /opt/ca
                  readOnly: true