apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airflow-db
  name: airflow-db
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-db
  template:
    metadata:
      labels:
        app: airflow-db
    spec:
      containers:
        - image: postgres:12
          name: airflow-db
          env:
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: airflow
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: airflow-db
  name: airflow-db
  namespace: airflow
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: airflow-db
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-db-credentials
  namespace: airflow
type: Opaque
stringData:
  password: mypassword
  username: myuser
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-db-connection
  namespace: airflow
type: Opaque
stringData:
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://myuser:mypassword@airflow-db:5432/airflow