apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common/airflow
  - db.yml
  - secrets.yml
  - dags

patchesStrategicMerge:
  - services-override.yml
  - deployments-override.yml
  - configsmap-override.yml