apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../qa/cqdg-orchestrations/airflow
  - db.yml
  - secrets.yml
  - deployments.yml
  - keycloak-backups.yml

patchesStrategicMerge:
  - services-override.yml
  - deployments-override.yml
  - configsmap-override.yml