#All secrets are dummy values for local environments
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: airflow
stringData:
  AIRFLOW__CORE__FERNET_KEY: BH_hFDEgojGoElDRVPqTTr_x0Xt9mCW_GP8ZynsMBg0=
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-flask-key
  namespace: airflow
stringData:
  AIRFLOW__WEBSERVER__SECRET_KEY: Ve+Vquvt4e1/tN4Qmx9lDg==
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-smtp
  namespace: airflow
stringData:
  AIRFLOW__SMTP__SMTP_HOST: localhost
  AIRFLOW__SMTP__SMTP_STARTTLS: "True"
  AIRFLOW__SMTP__SMTP_SSL: "False"
  AIRFLOW__SMTP__SMTP_PORT: "25"
  AIRFLOW__SMTP__SMTP_MAIL_FROM: airflow@example.com
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: airflow
stringData:
  var.json: |
    {}
  conn.json: |
    {}
  users.json: |
    [
      {
        "username": "admin",
        "firstname": "admin",
        "lastname": "admin",
        "role": "Admin",
        "email": "admin@admin.admin",
        "password": "admin"
      }
    ]