---
apiVersion: batch/v1
kind: Job
metadata:
  name: configure-arranger-2021.2
spec:
  backoffLimit: 4
  template:
    metadata:
      name: configure-arranger
    spec:
      restartPolicy: Never
      containers:
        - name: configure-arranger
          image: curlimages/curl
          command:
            - /bin/sh
            - -c
            - |
              curl -vvv -XDELETE "http://elasticsearch-workers:9200/arranger-projects";
              curl -vvv -XDELETE "http://elasticsearch-workers:9200/arranger-projects-cqdg";
              curl -vvv -XPOST "http://elasticsearch-workers:9200/arranger-projects/_doc/cqdg" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/cqdg-entry";
              curl -vvv -XPUT "http://elasticsearch-workers:9200/arranger-projects-cqdg" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/cqdg-mappings";
              curl -vvv -XPOST "http://elasticsearch-workers:9200/arranger-projects-cqdg/_doc/studies" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/studies-index";
              curl -vvv -XPOST "http://elasticsearch-workers:9200/arranger-projects-cqdg/_doc/donors" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/donors-index";
              curl -vvv -XPOST "http://elasticsearch-workers:9200/arranger-projects-cqdg/_doc/files" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/files-index";
          volumeMounts:
            - mountPath: /opt/curl-bodies
              name: configure-arranger
              readOnly: true
      volumes:
        - name: configure-arranger
          configMap:
            name: configure-arranger