---
apiVersion: batch/v1
kind: Job
metadata:
  name: configure-arranger-2021.2
spec:
  backoffLimit: 4
  template:
    metadata:
      name: configure-arranger
    spec:
      restartPolicy: Never
      containers:
        - name: configure-arranger
          image: curlimages/curl
          command:
            - /bin/sh
            - -c
            - -e
            - |
              curl -vvv -XDELETE "http://elasticsearch-workers:9200/arranger-projects";
              curl -vvv -XDELETE "http://elasticsearch-workers:9200/arranger-projects-cqdg";
              curl -vvv -XPOST "http://elasticsearch-workers:9200/arranger-projects/_doc/cqdg" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/cqdg-entry";
              curl -vvv -XPUT "http://elasticsearch-workers:9200/arranger-projects-cqdg" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/cqdg-mappings";
              curl -vvv -XPOST "http://elasticsearch-workers:9200/arranger-projects-cqdg/_doc/studies" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/studies-index";
              curl -vvv -XPOST "http://elasticsearch-workers:9200/arranger-projects-cqdg/_doc/donors" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/donors-index";
              curl -vvv -XPOST "http://elasticsearch-workers:9200/arranger-projects-cqdg/_doc/files" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/files-index";
          volumeMounts:
            - name: cqdg-entry
              mountPath: /opt/curl-bodies
              subPath: cqdg-entry.json
              readOnly: true
            - name: cqdg-mappings
              mountPath: /opt/curl-bodies
              subPath: cqdg-mappings.json
              readOnly: true
            - name: donors-index
              mountPath: /opt/curl-bodies
              subPath: donors-index.json
              readOnly: true
            - name: files-index
              mountPath: /opt/curl-bodies
              subPath: files-index.json
              readOnly: true
            - name: studies-index
              mountPath: /opt/curl-bodies
              subPath: studies-index.json
              readOnly: true
      volumes:
        - name: cqdg-entry
          configMap:
            name: cqdg-entry
            items:
            - key: cqdg-entry.json
              path: cqdg-entry.json
        - name: cqdg-mappings
          configMap:
            name: cqdg-mappings
            items:
            - key: cqdg-mappings.json
              path: cqdg-mappings.json
        - name: donors-index
          configMap:
            name: donors-index
            items:
            - key: donors-index.json
              path: donors-index.json
        - name: files-index
          configMap:
            name: files-index
            items:
            - key: files-index.json
              path: files-index.json
        - name: studies-index
          configMap:
            name: studies-index
            items:
            - key: studies-index.json
              path: studies-index.json