---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: keycloak-jars
spec:
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: plan
              env:
                - name: GIT_REPO
                  value: https://github.com/Ferlab-Ste-Justine/cqdg-keycloak.git
                - name: GIT_BRANCH
                  value: test
                - name: S3_ENDPOINT
                  value: https://esc.calculquebec.ca:8080
                - name: S3_REGION
                  value: RegionOne
          containers:
            - name: push
              env:
                - name: S3_ENDPOINT
                  value: https://esc.calculquebec.ca:8080
                - name: S3_REGION
                  value: RegionOne
            - name: prune
              env:
                - name: S3_ENDPOINT
                  value: https://esc.calculquebec.ca:8080
                - name: S3_REGION
                  value: RegionOne