apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cqdg-orchestrations/keycloak-jars-to-s3-job
  
patchesStrategicMerge:
  - jobs.yml

configMapGenerator:
  - name: keycloak-build-artifacts
    options:
      disableNameSuffixHash: true
    files:
      - build_list.json