---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
configMapGenerator:
  - name: airflow-dag-me
    options:
      disableNameSuffixHash: true
    files:
      - dagme.py
  - name: airflow-dag-me-too
    options:
      disableNameSuffixHash: true
    files:
      - dagmetoo.py