---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portal
  name: portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - image: ferlabcrsj/cqdg-portal:__UNDEFINED__
          name: portal
          resources:
            requests:
              memory: "256Mi"
              cpu: '0.50'
            limits:
              memory: "512Mi"
              cpu: '1.00'
          envFrom:
            - configMapRef:
                name: cqdg-portal-configs