apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30900
  selector:
    app: minio