apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: id-service

resources:
  - ../cqdg-orchestrations/id-service
  - backups

patchesStrategicMerge:
  - deployments-overrides.yml