apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - deployments.yml
  - services.yml
  - ingress.yml

configMapGenerator:
  - name: cqdg-portal-configs
    options:
      disableNameSuffixHash: false
    literals:
      - API_URL=https://data-api.dev.cqdg.ferlab.bio
      - KEYCLOAK_URL=https://auth.dev.cqdg.ferlab.bio/auth/