apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: 'true'
  labels:
    app: clinical-data
  name: clinical-data
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clinical-data
  template:
    metadata:
      labels:
        app: clinical-data
    spec:
      imagePullSecrets:
        - name: images-pull
      volumes:
        - name: ca-certificate
          secret:
            secretName: ca-certificate
            defaultMode: 0555
      containers:
      - image: ferlabcrsj/cqdg-clinical-data-service:3b0bc2e65aee8df24512cdf55e71fb757d084864
        name: clinical-data
        env:
          - name: LOG_LEVEL
            value: info
          - name: TYPEORM_USERNAME
            valueFrom:
              secretKeyRef:
                name: clinical-data-service-db-credentials
                key: username
          - name: TYPEORM_PASSWORD
            valueFrom:
              secretKeyRef:
                name: clinical-data-service-db-credentials
                key: password
        envFrom:
          - configMapRef:
              name: clinical-data-configs
          - configMapRef:
              name: clinical-data-service-db-connection
          - configMapRef:
              name: clinical-data-service-db-connection-tls
          - secretRef:
              name: s3-credentials
          - secretRef:
              name: clinical-data-keycloak-credentials
          - secretRef:
              name: clinical-data-lectern-credentials
          - secretRef:
              name: clinical-data-monitor-credentials
        volumeMounts:
          - name: ca-certificate
            mountPath: /opt/ca
            readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: '1.0'
          limits:
            memory: "512Mi"
            cpu: '2.0'
