apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yml
  - deployments.yml
  - services.yml

configMapGenerator:
  - name: clinical-data-configs
    options:
      disableNameSuffixHash: false
    literals:
      - AUTH_ENABLED=true
      - AUTH_CLIENT_ID=cqdg-system
      - AUTH_SERVER_URL=https://auth.qa.cqdg.ferlab.bio
      - AUTH_REALM=CQDG
      - LECTERN_SERVER_URL=https://schema.qa.cqdg.ferlab.bio
      - LECTERN_DICTIONARY_NAME="CQDG Data Dictionary"
      - LECTERN_DEFAULT_LANGUAGE=en
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=clinical-data-service-db
      - TYPEORM_DATABASE=clinical-data-service
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=false
      - TYPEORM_LOGGER=advanced-console
      - S3_SIGNIN_REGION=RegionOne
      - S3_BUCKET_NAME=clinical-data-service-qa
      - S3_SERVICE_ENDPOINT=https://esc.calculquebec.ca:8080
      - APP_HOST=clinical-data-api.qa.cqdg.ferlab.bio
      - APP_SCHEMA=https
      - APP_ROUTE_PREFIX=/api
      - APP_BANNER=true
      - FILE_UPLOAD_MAX_SIZE_MB=50
      - FILE_UPLOAD_MAX_NB_OF_FILES=11
      - FILE_UPLOAD_ALLOWED_MIMETYPES=text/tab-separated-values,text/csv
      - CACHE_CERT_TTL_IN_SECONDS=300
      - LOG_LEVEL=info
      - LOG_OUTPUT=combined
      - TYPEORM_MIGRATIONS=src/database/migrations/**/*.ts
      - TYPEORM_MIGRATIONS_DIR=src/database/migrations
      - TYPEORM_ENTITIES=src/api/models/**/*.ts
      - TYPEORM_ENTITIES_DIR=src/api/models
      - TYPEORM_SEEDING_FACTORIES=src/database/factories/**/*.ts
      - TYPEORM_SEEDING_SEEDS=src/database/seeds/**/*.ts
      - CONTROLLERS=src/api/controllers/**/*Controller.ts
      - MIDDLEWARES=src/api/middlewares/**/*Middleware.ts
      - INTERCEPTORS=src/api/interceptors/**/*Interceptor.ts
      - SUBSCRIBERS=src/api/subscribers/**/*Subscriber.ts
      - RESOLVERS=src/api/resolvers/**/*Resolver.ts
      - GRAPHQL_ENABLED=true
      - GRAPHQL_ROUTE=/graphql
      - GRAPHQL_EDITOR=true
      - SWAGGER_ENABLED=true
      - SWAGGER_ROUTE=/swagger
      - MONITOR_ENABLED=true
      - MONITOR_ROUTE=/monitor
      - RULES_LOCATION=rules
      - ES_HOSTS=http://elasticsearch-workers:9200