apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  template:
    spec:
      imagePullSecrets:
        - name: images-pull
      containers:
        - name: auto-updater
          env:
            - name: S3_ENDPOINT
              value: https://esc.calculquebec.ca:8080
            - name: S3_REGION
              value: RegionOne