apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cqdg-orchestrations/keycloak-with-jar-autodeploy
  - ingress.yml
  - jobs.yml

patchesStrategicMerge:
  - clin-theme.yml
  - jars.yml

configMapGenerator:
  - name: jars-list
    options:
      disableNameSuffixHash: true
    files:
      - jars_list.json