---
apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-id-service-db
spec:
  backoffLimit: 4
  activeDeadlineSeconds: 600
  template:
    spec:
      containers:
      - name: initialize-id-service-db
        image: postgres:12
        envFrom:
          - configMapRef:
              name: id-service-db-connection
          - configMapRef:
              name: id-service-db-connection-tls
        workingDir: /opt
        command:
          - psql
        args:
          - -f
          - id-service-schema.sql
        volumeMounts:
          - name: id-service-schema
            mountPath: /opt
            readOnly: true
      restartPolicy: Never
      volumes:
        - name: id-service-schema
          configMap:
            name: id-service-schema