---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: terraform-scripts
    namespace: terraform
    options:
      disableNameSuffixHash: true
    files:
      - clone.sh
      - apply.sh