apiVersion: v1
kind: Pod
metadata:
  labels: {}
spec:
  containers:
  - args: []
    command: []
    env:
    - name: AIRFLOW__CORE__EXECUTOR
      value: LocalExecutor
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    envFrom:
    - configMapRef:
        name: airflow-config-core
    - configMapRef:
        name: airflow-config-secrets
    - configMapRef:
        name: airflow-config-cli
    - configMapRef:
        name: airflow-config-api
    - configMapRef:
        name: airflow-config-operators
    - configMapRef:
        name: airflow-config-webserver
    - configMapRef:
        name: airflow-config-email
    - configMapRef:
        name: airflow-config-scheduler
    - secretRef:
        name: airflow-smtp
    - secretRef:
        name: airflow-smtp
    image: apache/airflow:1.10.14-python3.7
    imagePullPolicy: IfNotPresent
    name: base
    ports: []
    volumeMounts:
    - mountPath: /home/airflow/airflow/logs
      name: airflow-logs
  hostNetwork: false
  imagePullSecrets: []
  initContainers: []
  nodeSelector: {}
  restartPolicy: Never
  securityContext:
    runAsUser: 50000
  serviceAccountName: default
  volumes:
  - emptyDir: {}
    name: airflow-logs
