apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt
spec:
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  dnsNames:
    - ops.cqdg.ferlab.bio
    - container-registry.ops.cqdg.ferlab.bio
