apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cqdg-orchestrations/hive-metastore
  - configs.yml

patchesStrategicMerge:
  - deployments.yml
  - service.yml
  - backups