apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: manage-airflow-users
  namespace: airflow
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: ca-certificate
              secret:
                secretName: postgres-qa-ca-certificate
                defaultMode: 0555
          containers:
            - name: manage-airflow-users
              env:
                - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
                  valueFrom:
                    secretKeyRef:
                      name: postgres-qa-airflow-connection
                      key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              volumeMounts:
                - name: ca-certificate
                  mountPath: /opt/ca
                  readOnly: true