---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  template:
    spec:
      imagePullSecrets:
        - name: images-pull
      initContainers:
        - name: db-init
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: postgres-qa-airflow-connection
                  key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          volumeMounts:
            - name: ca-certificate
              mountPath: /opt/ca
              readOnly: true
      containers:
        - name: airflow-scheduler
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: postgres-qa-airflow-connection
                  key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
              readOnly: true
            - name: ca-certificate
              mountPath: /opt/ca
              readOnly: true
      volumes:
        - name: dags
          hostPath:
            path: /opt/airflow-dags
        - name: ca-certificate
          secret:
            secretName: postgres-qa-ca-certificate
            defaultMode: 0555
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  template:
    spec:
      imagePullSecrets:
        - name: images-pull
      volumes:
        - name: dags
          hostPath:
            path: /opt/airflow-dags
      containers:
        - name: airflow-webserver
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: postgres-qa-airflow-connection
                  key: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
              readOnly: true
            - name: ca-certificate
              mountPath: /opt/ca
              readOnly: true
      volumes:
        - name: ca-certificate
          secret:
            secretName: postgres-qa-ca-certificate
            defaultMode: 0555