apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - ../cqdg-orchestrations/airflow
#  - dag-configs
#  - ingress.yml
  - access
  - backups

#patchesStrategicMerge:
#  - deployments-override.yml
#  - configsmap-override.yml