apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cqdg-orchestrations/airflow
  - ingress.yml

patchesStrategicMerge:
  - deployments-override.yml
  - configsmap-override.yml