apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:	
    fluxcd.io/automated: 'true'
  name: keycloak
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: images-pull
      containers:
        - name: keycloak
          image: ferlabcrsj/cqdg-keycloak:1c259e9380d4d8ac0391d293c7267c1f7cb81178
          env:
            - name: ORCID_URL
              value: 'https://sandbox.orcid.org'
            - name: CACHE_OWNERS_COUNT
              value: "1"
            - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
              value: "1"
