apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:	
    fluxcd.io/automated: 'true'
  name: keycloak
spec:
  replicas: 3
  template:
    spec:
      imagePullSecrets:
        - name: images-pull
      containers:
        - name: keycloak
          image: ferlabcrsj/cqdg-keycloak:1c259e9380d4d8ac0391d293c7267c1f7cb81178
          env:
            - name: ORCID_URL
              value: 'https://sandbox.orcid.org'
            - name: CACHE_OWNERS_COUNT
              value: "2"
            - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
              value: "2"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-qa-keycloak-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-qa-keycloak-credentials
                  key: password
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: postgres-server-qa
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: keycloak_dev
            - name: JDBC_PARAMS
              value: 'sslmode=verify-full&sslrootcert=/opt/ca/ca.pem'
