apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../common/keycloak
  - ../cqdg-orchestrations/keycloak
  - ingress.yml

patchesStrategicMerge:
  - clin-theme.yml
  - cqdg-keycloak.yml
