---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:	
    fluxcd.io/automated: 'true'
  name: arranger
spec:
  template:
    spec:
      imagePullSecrets:
        - name: images-pull
      containers:
        - image: ferlabcrsj/cqdg-arranger:fba9ddc0ce38c200c0f2e3de3922fce0395a11df
          name: arranger