---
apiVersion: batch/v1
kind: Job
metadata:
  name: configure-arranger-19-11-2020
spec:
  backoffLimit: 4
  template:
    metadata:
      name: configure-arranger-19-11-2020
    spec:
      restartPolicy: Never
      containers:
        - name: configure-arranger-19-11-2020
          image: curlimages/curl
          command:
            - /bin/sh
            - -c
            - |
              curl -XPOST "http://elasticsearch-workers:9200/arranger-projects/_doc/cqdg" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/cqdg-entry";
              curl -XPUT "http://elasticsearch-workers:9200/arranger-projects-cqdg" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/cqdg-mappings";
              curl -XPOST "http://elasticsearch-workers:9200/arranger-projects-cqdg/_doc/cases" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/cases-index";
              curl -XPUT "http://elasticsearch-workers:9200/arranger-projects-cqdg/_doc/files" -H 'Content-Type: application/json' --data "@/opt/curl-bodies/files-index";
          volumeMounts:
            - mountPath: /opt/curl-bodies
              name: configure-arranger-19-11-2020
              readOnly: true
      volumes:
        - name: configure-arranger-19-11-2020
          configMap:
            name: configure-arranger-19-11-2020