apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: keycloak-jars
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: keycloak-build-artifacts
              configMap:
                name: keycloak-build-artifacts
                defaultMode: 0444
            - name: repo
              emptyDir: {}
          restartPolicy: Never
          initContainers:
            - name: plan
              image: chusj/binary-artifacts:ddc6235e3ac37a8900f3e66192ef2800a14e4152
              imagePullPolicy: IfNotPresent
              command: ["python", "/opt/scripts/plan.py"]
              volumeMounts:
                - name: keycloak-build-artifacts
                  mountPath: /opt/build_list
                  readOnly: true
                - name: repo
                  mountPath: /opt/repo
              envFrom:
                - secretRef:
                    name: s3-credentials
              env:
                - name: GIT_REPO
                  value: https://github.com/Ferlab-Ste-Justine/cqdg-keycloak.git
                - name: GIT_BRANCH
                  value: main
                - name: S3_ENDPOINT
                  value: http://minio:9000
                - name: S3_REGION
                  value: myregion
            - name: build
              image: openjdk:11.0-buster
              imagePullPolicy: IfNotPresent
              command: ["/opt/repo/RUN_BUILD.sh"]
              volumeMounts:
                - name: repo
                  mountPath: /opt/repo
          containers:
            - name: push
              image: chusj/binary-artifacts:ddc6235e3ac37a8900f3e66192ef2800a14e4152
              imagePullPolicy: IfNotPresent
              command: ["python", "/opt/scripts/push.py"]
              volumeMounts:
                - name: keycloak-build-artifacts
                  mountPath: /opt/build_list
                  readOnly: true
                - name: repo
                  mountPath: /opt/repo
              envFrom:
                - secretRef:
                    name: s3-credentials
              env:
                - name: GIT_REPO
                  value: https://github.com/Ferlab-Ste-Justine/cqdg-keycloak.git
                - name: GIT_BRANCH
                  value: main
                - name: S3_ENDPOINT
                  value: http://minio:9000
                - name: S3_REGION
                  value: myregion
            - name: prune
              image: chusj/binary-artifacts:ddc6235e3ac37a8900f3e66192ef2800a14e4152
              imagePullPolicy: IfNotPresent
              command: ["python", "/opt/scripts/prune.py"]
              volumeMounts:
                - name: keycloak-build-artifacts
                  mountPath: /opt/build_list
                  readOnly: true
              envFrom:
                - secretRef:
                    name: s3-credentials
              env:
                - name: S3_ENDPOINT
                  value: http://minio:9000
                - name: S3_REGION
                  value: myregion
                - name: MAX_ARTIFACTS_AMOUNT
                  value: "2"
