apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jobs.yml
  - secrets.yml

configMapGenerator:
  - name: keycloak-build-artifacts
    options:
      disableNameSuffixHash: true
    files:
      - build_list.json