apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../qa/cqdg-orchestrations/hive-metastore
  - configs.yml
  - db.yml
  - secrets.yml

patchesStrategicMerge:
  - deployments.yml