---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: git-autosync
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: git-autosync
      containers:
      - image: chusj/git-autosync:3b73ec728657bf5e7463a561b9cbb1cb47cedabd
        name: git-autosync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: docs
      containers:
      - image: chusj/cqdg-docs:d309acc3f4ad65771f89a01f989b4e6e067b4623
        name: docs
