---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: git-autosync
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: git-autosync
      containers:
      - image: chusj/git-autosync:3b73ec728657bf5e7463a561b9cbb1cb47cedabd
        name: git-autosync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: docs
      containers:
      - image: chusj/cqdg-docs:9331cafd5febf959b373639381b96701a52a19ac
        name: docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hive-metastore
      containers:
      - image: chusj/hive-metastore:2b05281a31f7feb82716ca3b303d37a700a4bb3c
        name: hive-metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: portal
      containers:
      - image: chusj/cqdg-portal-ui:b212a3d6b96bb2429cc64483ae9b37763a7b00bf
        name: portal
