---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: git-autosync
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: git-autosync
      containers:
      - image: ferlabcrsj/git-autosync:1.2.0
        name: git-autosync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arranger
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: arranger
      containers:
      - image: ferlabcrsj/cqdg-arranger:668c401f6d1c2239d474d19fd27f1dd66082ca83
        name: arranger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-data
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clinical-data
      containers:
      - image: ferlabcrsj/cqdg-clinical-data-service:1ade8421fdbde84379048387c9ac41265b80b243
        name: clinical-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagrid-service
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: datagrid-service
      containers:
      - image: ferlabcrsj/datagrid-service:0505e5b8349ff1632fb967fe8c190bf6a2d25ae4
        name: datagrid-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: docs
      containers:
      - image: ferlabcrsj/cqdg-docs:a2a0fef4e5114cd3791e23826147962e9180dc93
        name: docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hive-metastore
      containers:
      - image: ferlabcrsj/hive-metastore:ba3d4e6d97baef31fb450cb6c75c73b19ec64fce
        name: hive-metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lectern
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: lectern
      containers:
      - image: ferlabcrsj/lectern:092cf118415efdcb159e96af64c365d6c0455bfe
        name: lectern
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: portal
      containers:
      - image: ferlabcrsj/cqdg-portal:4d7f51c7780d74aef206f5660cbe78fe5877ce1d
        name: portal
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: keycloak
      containers:
      - image: ferlabcrsj/cqdg-keycloak:bc9fed459abceb24d924e5d0fb4172a4032fcec9
        name: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-service
  namespace: id-service
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: id-service
      containers:
      - image: ferlabcrsj/id-service:6b8450941af27b83c511244975f81eda33919957
        name: id-service
