---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: git-autosync
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: git-autosync
      containers:
      - image: chusj/git-autosync:37ed929623b381597b3ece56d2aa46bfb5a290f5
        name: git-autosync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: docs
      containers:
      - image: chusj/cqdg-docs:9f03b8c66cfa9c13a105803ad873f61c464f168b
        name: docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hive-metastore
      containers:
      - image: chusj/hive-metastore:7508c20ef44952f1ee2af91a26822b6efc10998f
        name: hive-metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: portal
      containers:
      - image: chusj/cqdg-portal-ui:84646a89ac4a1d19271893f3fcd46de8442f7d73
        name: portal
