---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arranger
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: arranger
      containers:
      - image: ferlabcrsj/cqdg-arranger:73a2a7775c7a120ead6c19df0867112e2fc350ad
        name: arranger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-data
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clinical-data
      containers:
      - image: ferlabcrsj/cqdg-clinical-data-service:1f139fcc3f151e43d7596f7c19adceec4d40a95c
        name: clinical-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagrid-service
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: datagrid-service
      containers:
      - image: ferlabcrsj/datagrid-service:314e9c588f21063f1b7932d5508ecc7d69fe260f
        name: datagrid-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: docs
      containers:
      - image: ferlabcrsj/cqdg-docs:dd9ddc5cc3093fce815e7aa1c4d756a49c87510f
        name: docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hive-metastore
      containers:
      - image: ferlabcrsj/hive-metastore:ba3d4e6d97baef31fb450cb6c75c73b19ec64fce
        name: hive-metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: portal
      containers:
      - image: ferlabcrsj/cqdg-portal:03780996a9a59a6dba7234624f0447496cbb8acb
        name: portal
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: keycloak
      containers:
      - image: ferlabcrsj/cqdg-keycloak:036e2287615b5647a565496bcca2f94c8fb33d68
        name: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-service
  namespace: id-service
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: id-service
      containers:
      - image: ferlabcrsj/id-service:5cc189e17854ce9f647b716083afc0167a5f8db4
        name: id-service
