---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arranger
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: arranger
      containers:
      - image: ferlabcrsj/cqdg-arranger:6211b3ae0011fce54847ed07c86bdd5e266de3ed
        name: arranger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-data
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clinical-data
      containers:
      - image: ferlabcrsj/cqdg-clinical-data-service:bc9fd908ccb3c561b66faf910a3e2d56e300d878
        name: clinical-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: docs
      containers:
      - image: ferlabcrsj/cqdg-docs:c911e1a8ad805fe0701201fdda358f8f5ddc6f04
        name: docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hive-metastore
      containers:
      - image: ferlabcrsj/hive-metastore:ba3d4e6d97baef31fb450cb6c75c73b19ec64fce
        name: hive-metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: portal
      containers:
      - image: ferlabcrsj/cqdg-portal:fa7c5e87a071ec70f15de14683f64658358844ea
        name: portal
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: keycloak
      containers:
      - image: ferlabcrsj/cqdg-keycloak:32e9789b8475e020cdec69a5403da8194575a001
        name: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-service
  namespace: id-service
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: id-service
      containers:
      - image: ferlabcrsj/id-service:6adbbdbe421c24b34675ecefa59a26aefa17c588
        name: id-service
