---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: git-autosync
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: git-autosync
      containers:
      - image: chusj/git-autosync:3b73ec728657bf5e7463a561b9cbb1cb47cedabd
        name: git-autosync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: docs
      containers:
      - image: chusj/cqdg-docs:45ec2a62363cd5f27672965a8b52802f8bcf33cc
        name: docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hive-metastore
      containers:
      - image: chusj/hive-metastore:2b05281a31f7feb82716ca3b303d37a700a4bb3c
        name: hive-metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: portal
      containers:
      - image: chusj/cqdg-portal-ui:de476a7ed8aa3b9a687064a186c1cef1bbac136c
        name: portal
