---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arranger
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: arranger
      containers:
      - image: ferlabcrsj/cqdg-arranger:6211b3ae0011fce54847ed07c86bdd5e266de3ed
        name: arranger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-data
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: clinical-data
      containers:
      - image: ferlabcrsj/cqdg-clinical-data-service:23616c0f9568ec03b18084a7743a8d67bec07b97
        name: clinical-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: docs
      containers:
      - image: ferlabcrsj/cqdg-docs:dd9ddc5cc3093fce815e7aa1c4d756a49c87510f
        name: docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: hive-metastore
      containers:
      - image: ferlabcrsj/hive-metastore:ba3d4e6d97baef31fb450cb6c75c73b19ec64fce
        name: hive-metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: portal
      containers:
      - image: ferlabcrsj/cqdg-portal:fa7c5e87a071ec70f15de14683f64658358844ea
        name: portal
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: keycloak
      containers:
      - image: ferlabcrsj/cqdg-keycloak:32e9789b8475e020cdec69a5403da8194575a001
        name: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-service
  namespace: id-service
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: id-service
      containers:
      - image: ferlabcrsj/id-service:b0226237c332d30cefef3c27510014896e568294
        name: id-service
